// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:4dbf45cd-e8de-4174-b1be-ffaba810ec31",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_RyTiBLgx2",
    "aws_user_pools_web_client_id": "181r5777q1h47fadfa3iumaiah",
    "aws_appsync_graphqlEndpoint": "https://amgsa5aperev7bgk5d2rn37muu.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-lng2h52cpvhrpiv33sl64xrxxy"
};


export default awsmobile;
